import Link from 'next/link'
import { ArrowRight, Activity, Gauge, Layers } from 'lucide-react'

import { NullMeterDemo } from '@/components/null-meter/null-meter-demo'
import { NullMeterLiveChat } from '@/components/null-meter/null-meter-live-chat'
import {
  PageHeader,
  PageHeaderDescription,
  PageHeaderHeading,
} from '@/components/page-header'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import type { LocaleOptions } from '@/lib/opendocs/types/i18n'

export const metadata = {
  title: 'Null Meter — live demo',
  description:
    'A three-layer gauge for AI sessions: hallucination index, null-state drift, and context fill. Type a prompt, get a real model reply, watch the meter score it live.',
}

const layers = [
  {
    icon: Activity,
    title: 'Hallucination Index',
    description:
      'Scores the current assistant turn against the V2 detector: confidence exceeding evidence, fabricated specificity, and fluency-over-content ratio. Pattern signal, not token signal.',
  },
  {
    icon: Layers,
    title: 'Null-State Drift',
    description:
      'Embedding-space distance between the current turn and the original system intent + first user request. Climbs when the model is coherent but no longer on task.',
  },
  {
    icon: Gauge,
    title: 'Context Fill',
    description:
      'Tokens used against the active model context window. The early warning for the other two layers — attention starts collapsing past ~80%.',
  },
]

const surfaces = [
  {
    title: 'Library hook',
    detail:
      'A useNullMeter() hook that wraps useChat from the AI SDK. Returns the three layers as a single object. Ships first.',
  },
  {
    title: 'VS Code extension',
    detail:
      'Status-bar gauge + webview panel for Copilot Chat and any registered model API. Highest signal for coding flow.',
  },
  {
    title: 'Browser extension',
    detail:
      'Overlay on chatgpt.com, claude.ai, gemini.google.com, and x.com (Grok). Reads DOM, scores each assistant turn locally.',
  },
  {
    title: 'CLI / dev-server overlay',
    detail:
      'Middleware for backend devs. Exposes a localhost dashboard for any model traffic running through the wrapper.',
  },
]

export default function NullMeterPage({
  params,
}: {
  params: { locale: LocaleOptions }
}) {
  void params

  return (
    <main className="container py-10">
      <PageHeader>
        <Badge variant="outline" className="mb-3">
          Live demo
        </Badge>
        <PageHeaderHeading>Null Meter</PageHeaderHeading>
        <PageHeaderDescription>
          Drift, hallucination, and context pressure as three separate axes,
          stacked into one gauge. Type a prompt, get a real model reply, watch
          each layer score the conversation turn-by-turn.
        </PageHeaderDescription>
      </PageHeader>

      <section className="mx-auto max-w-6xl space-y-10">
        <Card>
          <CardHeader>
            <CardTitle>Live chat</CardTitle>
            <CardDescription>
              Type anything. The reply is generated by a real OpenAI model. The
              V2 detector scores it. Drift is real embedding distance from your
              first message. Context fill is real token usage.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <NullMeterLiveChat />
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Scripted scenarios</CardTitle>
            <CardDescription>
              Pre-recorded representations of failure modes already documented
              in the evidence pack. Useful for seeing the shape of each layer
              without spending a live API call.
            </CardDescription>
          </CardHeader>
          <CardContent>
            <NullMeterDemo />
          </CardContent>
        </Card>

        <section className="grid gap-4 md:grid-cols-3">
          {layers.map((layer) => (
            <Card key={layer.title}>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-base">
                  <layer.icon className="size-4" />
                  {layer.title}
                </CardTitle>
              </CardHeader>
              <CardContent className="text-sm leading-6 text-muted-foreground">
                {layer.description}
              </CardContent>
            </Card>
          ))}
        </section>

        <Card>
          <CardHeader>
            <CardTitle>Why three layers, not one</CardTitle>
            <CardDescription>
              Each layer fails differently. The relationship between them is
              the actual diagnostic.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3 text-sm leading-6 text-muted-foreground">
            <p>
              <span className="font-mono text-xs text-foreground">
                Context fill rising alone
              </span>{' '}
              — a compact is coming. Not yet a behavioral problem.
            </p>
            <p>
              <span className="font-mono text-xs text-foreground">
                Hallucination spiking with low context
              </span>{' '}
              — the model is fabricating fresh, not because it ran out of room.
              Investigate the prompt shape.
            </p>
            <p>
              <span className="font-mono text-xs text-foreground">
                Drift climbing with low hallucination
              </span>{' '}
              — the model is coherent but has forgotten what you asked for. The
              user usually does not notice.
            </p>
            <p>
              <span className="font-mono text-xs text-foreground">
                All three rising together
              </span>{' '}
              — stop. Start a new session. Do not ship the next turn.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Surfaces</CardTitle>
            <CardDescription>
              One scoring engine. Four thin clients. The detector is the same
              V2 export already shipped in @alephonenull/eval.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4 md:grid-cols-2">
            {surfaces.map((surface) => (
              <div
                key={surface.title}
                className="rounded-md border border-border bg-muted/20 p-4"
              >
                <p className="font-mono text-xs text-foreground">
                  {surface.title}
                </p>
                <p className="mt-2 text-sm leading-6 text-muted-foreground">
                  {surface.detail}
                </p>
              </div>
            ))}
          </CardContent>
        </Card>

        <Alert>
          <Gauge className="size-4" />
          <AlertTitle>Status</AlertTitle>
          <AlertDescription>
            The live chat above calls a real OpenAI model and scores the reply
            with the V2 detector shipped in @alephonenull/eval. The library
            hook, VS Code extension, and browser extension are the next ship
            targets — same scoring engine, different surfaces.
          </AlertDescription>
        </Alert>

        <div className="flex flex-wrap gap-3">
          <Button asChild>
            <Link href="/evidence">
              Review the evidence pack
              <ArrowRight className="ml-2 size-4" />
            </Link>
          </Button>
          <Button asChild variant="outline">
            <Link href="/roadmap">View the roadmap</Link>
          </Button>
        </div>
      </section>
    </main>
  )
}
