import Link from 'next/link'
import {
  ArrowRight,
  BarChart3,
  FileJson,
  FlaskConical,
  GitBranch,
  ShieldCheck,
} from 'lucide-react'

import {
  PageHeader,
  PageHeaderDescription,
  PageHeaderHeading,
} from '@/components/page-header'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  EVIDENCE_LAST_UPDATED,
  EVIDENCE_METRICS,
  EVIDENCE_REPO_URL,
} from '@/lib/evidence/metrics'

// Validation run constants. Values are copied verbatim from the JSON reports
// generated by the 2026-07-21 rerun:
//   packages/npm/validation/v3/results/v3.0.0-internal.1.json
//   packages/npm/validation/v3/results/anthropic-red-team-proxy.json
// Do not edit by hand without rerunning both evaluations.
const VALIDATION_RUN_DATE = '2026-07-21'
const VALIDATION_ENGINE_DIGEST =
  '92a9b513667580f03ace491a10983e1f3089e630b6fa8d76d2967bf6e5d2d042'
const VALIDATION_RESULTS_BASE_URL =
  'https://github.com/purposefulmaker/alephonenull/blob/main/packages/npm/validation/v3/results'

const validationRuns = [
  {
    title: 'Internal contrast evaluation',
    verdict: 'PASS' as const,
    scope: '80 synthetic conversations (developer-authored contrast pairs)',
    reportFile: 'v3.0.0-internal.1.md',
    command: 'pnpm validate:v3',
    // holdout.qEvaluation + holdout.confidenceIntervals95
    metrics: [
      { label: 'AUROC', estimate: '0.995', interval: '0.978–1.000' },
      { label: 'Sensitivity', estimate: '0.900', interval: '0.750–1.000' },
      { label: 'Specificity', estimate: '1.000', interval: '1.000–1.000' },
    ],
    caveat:
      'Developer-authored synthetic fixtures written with knowledge of the detector taxonomy. Useful for reproducibility and regression detection, not independent evidence of safety.',
  },
  {
    title: 'External Anthropic red-team proxy',
    verdict: 'FAIL' as const,
    scope: '2,000 independently authored conversations (HH-RLHF red-team attempts)',
    reportFile: 'anthropic-red-team-proxy.md',
    command:
      'node packages/npm/validation/v3/run-anthropic-proxy.mjs <red_team_attempts.jsonl.gz>',
    // evaluation + confidenceIntervals95
    metrics: [
      { label: 'AUROC', estimate: '0.465', interval: '0.441–0.489' },
      { label: 'Sensitivity', estimate: '0.244', interval: '0.217–0.271' },
      { label: 'Specificity', estimate: '0.723', interval: '0.696–0.752' },
    ],
    caveat:
      'The proxy uses human attack-success ratings, not V3 category labels, so it is an imperfect proxy. The failure still shows Q is not currently a general harm score and does not replace ROC/AUROC analysis or deployment-specific validation.',
  },
]

const corpusMetrics = [
  {
    label: 'Fixture files',
    value: String(EVIDENCE_METRICS.fixtureFiles),
    detail: 'Canonical JSONL files in the preliminary evidence corpus.',
  },
  {
    label: 'Labeled turns',
    value: String(EVIDENCE_METRICS.labeledTurns),
    detail: 'Each turn includes input, output, labels, and review notes.',
  },
  {
    label: 'Controls',
    value: String(EVIDENCE_METRICS.controls),
    detail: 'Expected-safe or bounded examples for false-positive review.',
  },
  {
    label: 'Positive turns',
    value: String(EVIDENCE_METRICS.positiveTurns),
    detail: 'Examples marked with one or more behavioral risk labels.',
  },
  {
    label: 'Observed labels',
    value: String(EVIDENCE_METRICS.observedLabels),
    detail: 'Distinct risk categories represented in the current corpus.',
  },
  {
    label: 'Control rate',
    value: EVIDENCE_METRICS.controlRate,
    detail: 'Share reserved for expected-safe or bounded examples.',
  },
]

const artifactFiles = [
  { name: 'README.md', purpose: 'Evidence pack overview and review path.' },
  {
    name: 'technical_memo.md',
    purpose: 'Preliminary findings and methodology limits.',
  },
  {
    name: 'scoring_rubric.md',
    purpose: 'Category definitions for repeatable label review.',
  },
  {
    name: 'V3_V3_ALIGNMENT.md',
    purpose: 'Current detector coverage and next validation targets.',
  },
  {
    name: 'manifest.json',
    purpose: 'Machine-readable corpus metadata and label counts.',
  },
  {
    name: 'benchmark.py',
    purpose: 'Reproducible corpus summary and optional engine comparison.',
  },
  {
    name: 'reproduce.sh',
    purpose: 'Shell entry point for rerunning the summary.',
  },
]

const scopeNotes = [
  {
    label: 'Fixture set',
    detail:
      'The corpus is built for behavioral category review, not provider ranking.',
  },
  {
    label: 'Four provider labels',
    detail:
      'Provider names are retained as provenance metadata for each labeled turn.',
  },
  {
    label: 'Distribution disclosed',
    detail:
      'Exact provider counts remain in the manifest and generated benchmark output.',
  },
]

const validationMilestones = [
  'Compare detector output against the labeled fixtures.',
  'Publish precision, recall, and F1 by category.',
  'Add independent second-rater review on a representative subset.',
  'Build a provider-balanced evaluation set before publishing comparative claims.',
]

export default function EvidencePage() {
  return (
    <main className="container py-10">
      <PageHeader>
        <Badge variant="outline" className="mb-3">
          preliminary evidence corpus
        </Badge>
        <PageHeaderHeading>Evidence and Reproducibility</PageHeaderHeading>
        <PageHeaderDescription>
          AlephOneNull publishes its current evidence as labeled fixtures,
          controls, scoring notes, and reproducibility scripts. The corpus is
          preliminary; its purpose is transparent review, not certification.
        </PageHeaderDescription>
      </PageHeader>

      <div className="mx-auto max-w-6xl">
        <div className="mb-8 flex flex-wrap gap-3">
          <Button asChild>
            <Link href={EVIDENCE_REPO_URL} target="_blank" rel="noreferrer">
              Open Evidence Pack
              <ArrowRight className="ml-2 size-4" />
            </Link>
          </Button>
          <Button variant="outline" asChild>
            <Link href="/about">Why This Exists</Link>
          </Button>
        </div>

      <section className="mb-12">
        <div className="mb-4">
          <h2 className="flex items-center gap-2 text-xl font-semibold text-foreground">
            <FlaskConical className="size-5" />
            Validation Results
          </h2>
          <p className="mt-1 text-sm text-muted-foreground">
            Both evaluations were rerun on {VALIDATION_RUN_DATE} against the
            current build. Engine source digest{' '}
            <span className="font-mono text-xs">
              {VALIDATION_ENGINE_DIGEST.slice(0, 12)}…
            </span>
            . The two results must always be cited together; see the{' '}
            <Link
              href="/docs/contract"
              className="underline underline-offset-2 hover:text-foreground"
            >
              V3 contract
            </Link>{' '}
            for what the scores do and do not mean.
          </p>
        </div>

        <div className="grid gap-8 lg:grid-cols-2">
          {validationRuns.map((run) => (
            <Card key={run.title}>
              <CardHeader>
                <CardTitle className="flex items-center justify-between gap-2">
                  {run.title}
                  <Badge
                    variant="outline"
                    className={
                      run.verdict === 'PASS'
                        ? 'border-emerald-300 text-emerald-700 dark:border-emerald-900 dark:text-emerald-400'
                        : 'border-red-300 text-red-700 dark:border-red-900 dark:text-red-400'
                    }
                  >
                    {run.verdict}
                  </Badge>
                </CardTitle>
                <CardDescription>{run.scope}</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <div className="space-y-2">
                  {run.metrics.map((metric) => (
                    <div
                      key={metric.label}
                      className="grid grid-cols-[1fr_auto_auto] items-baseline gap-3 rounded-md border bg-muted/20 p-3"
                    >
                      <p className="text-sm font-medium text-foreground">
                        {metric.label}
                      </p>
                      <p className="font-mono text-sm text-foreground">
                        {metric.estimate}
                      </p>
                      <p className="font-mono text-xs text-muted-foreground">
                        95% CI {metric.interval}
                      </p>
                    </div>
                  ))}
                </div>
                <p className="text-sm leading-6 text-muted-foreground">
                  {run.caveat}
                </p>
                <div className="rounded-md border bg-slate-950 p-3 font-mono text-xs text-slate-100">
                  <p>{run.command}</p>
                </div>
                <Link
                  href={`${VALIDATION_RESULTS_BASE_URL}/${run.reportFile}`}
                  target="_blank"
                  rel="noreferrer"
                  className="inline-flex items-center gap-1 text-sm underline underline-offset-2 text-muted-foreground hover:text-foreground"
                >
                  Raw result file
                  <ArrowRight className="size-3.5" />
                </Link>
              </CardContent>
            </Card>
          ))}
        </div>
      </section>

      <Alert className="mb-8 border-amber-200 bg-amber-50 dark:border-amber-900/50 dark:bg-amber-950/20">
        <ShieldCheck className="size-4 text-amber-700 dark:text-amber-400" />
        <AlertTitle className="text-amber-900 dark:text-amber-200">
          Claim Boundary
        </AlertTitle>
        <AlertDescription className="text-amber-800 dark:text-amber-300">
          This corpus supports detector development, category-presence claims,
          and reproducibility review. It does not establish population base
          rates, clinical efficacy, legal causation, provider ranking, or
          production safety.
        </AlertDescription>
      </Alert>

      <section className="mb-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        {corpusMetrics.map((metric) => (
          <Card key={metric.label}>
            <CardHeader className="pb-3">
              <CardTitle className="text-3xl font-bold text-foreground">
                {metric.value}
              </CardTitle>
              <CardDescription>{metric.label}</CardDescription>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-muted-foreground">{metric.detail}</p>
            </CardContent>
          </Card>
        ))}
      </section>

      <p className="mb-12 text-xs text-muted-foreground">
        Source of record:{' '}
        <Link
          href={EVIDENCE_REPO_URL}
          target="_blank"
          rel="noreferrer"
          className="underline underline-offset-2 hover:text-foreground"
        >
          public repository
        </Link>
        . Counts reflect the labeled fixture set as of {EVIDENCE_LAST_UPDATED}.
      </p>

      <section className="mb-12 grid gap-8 lg:grid-cols-[1.1fr_0.9fr]">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <FileJson className="size-5" />
              Evidence Pack Contents
            </CardTitle>
            <CardDescription>
              Public materials that support the current research claims.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {artifactFiles.map((file) => (
              <div
                key={file.name}
                className="grid gap-1 rounded-md border bg-muted/20 p-3 md:grid-cols-[13rem_1fr]"
              >
                <p className="font-mono text-xs text-foreground">{file.name}</p>
                <p className="text-sm text-muted-foreground">{file.purpose}</p>
              </div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <BarChart3 className="size-5" />
              Corpus Scope
            </CardTitle>
            <CardDescription>
              A labeled fixture corpus, not a provider benchmark.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm leading-6 text-muted-foreground">
              The current release is meant to make risk categories inspectable
              and reproducible. It should not be read as a market-share sample,
              provider scorecard, or statistical rate study.
            </p>
            <div className="space-y-3">
              {scopeNotes.map((note) => (
                <div
                  key={note.label}
                  className="rounded-md border bg-muted/20 p-3"
                >
                  <p className="text-sm font-medium text-foreground">
                    {note.label}
                  </p>
                  <p className="mt-1 text-sm text-muted-foreground">
                    {note.detail}
                  </p>
                </div>
              ))}
            </div>
          </CardContent>
        </Card>
      </section>

      <section className="mb-12 grid gap-8 lg:grid-cols-2">
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <GitBranch className="size-5" />
              Reproducibility
            </CardTitle>
            <CardDescription>
              The benchmark can be rerun from the public evidence pack.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-4 text-sm text-muted-foreground">
            <div className="rounded-md border bg-slate-950 p-4 font-mono text-xs text-slate-100">
              <p>git clone https://github.com/purposefulmaker/alephonenull</p>
              <p>cd alephonenull/capture</p>
              <p>python benchmark.py --labels . --out out/RESULTS.md</p>
              <p>./reproduce.sh</p>
            </div>
            <p>
              The script summarizes the current human-labeled corpus. If
              detector output is supplied, it can also report category-level
              comparison metrics.
            </p>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>Next Validation Milestones</CardTitle>
            <CardDescription>
              Planned work before stronger evaluation claims.
            </CardDescription>
          </CardHeader>
          <CardContent className="space-y-3">
            {validationMilestones.map((step, index) => (
              <div
                key={step}
                className="flex gap-3 rounded-md border bg-muted/20 p-3 text-sm text-muted-foreground"
              >
                <span className="font-mono text-xs text-foreground">
                  {index + 1}
                </span>
                <p>{step}</p>
              </div>
            ))}
          </CardContent>
        </Card>
      </section>

      <div className="rounded-lg border border-blue-200 bg-blue-50 p-6 dark:border-blue-900/50 dark:bg-blue-950/20">
        <h2 className="mb-2 font-semibold text-blue-950 dark:text-blue-100">
          Public Evidence Summary
        </h2>
        <p className="mb-4 max-w-3xl text-sm leading-6 text-blue-900 dark:text-blue-200">
          The corpus size, labels, controls, scope boundary, artifact index,
          and validation milestones are presented here for readers who want the
          evidence before opening the repository. GitHub remains the source of
          record.
        </p>
        <div className="flex flex-wrap gap-3">
          <Button variant="outline" asChild>
            <Link href="/docs/framework">Review Framework</Link>
          </Button>
          <Button variant="outline" asChild>
            <Link href="/technical-spec">Technical Spec</Link>
          </Button>
        </div>
      </div>
      </div>
    </main>
  )
}
